version: '3'

services:

    vigrom-nginx:
        build: ./docker/nginx
        container_name: vigrom-nginx
        links:
            - vigrom-php
        expose:
            - 80
            - 443
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./public:/var/www/vigrom/public

    vigrom-php:
        container_name: vigrom-php
        environment:
            - PHP_IDE_CONFIG=serverName=vigrom
            - JWT_PRIVATE_KEY_PATH
            - JWT_PUBLIC_KEY_PATH
            - JWT_PASSPHRASE
        build: ./docker/php
        volumes:
            - ./:/var/www/vigrom
            - ~/.ssh:/var/www/.ssh

    vigrom-postgres:
        container_name: vigrom-postgres
        build: ./docker/postgres
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - ${PG_PORT}:5432
